// константа для общей темы приложения. Подключаем через themeProvider, после чего можно будет в стилизованных компонентах обращаться к этим константам через props.theme
export const defaultTheme = {
  colorBlackForText: "#333333",
  colorWhite: "#ffffff",
  colorGray: "#f6f6f6",
  colorForLightBackground: "#fff6d9",
  colorForDarkBackground: "#ffeead",
  colorForNewIcon: "#ffb334",
  colorForSoftIcon: "#7fc92e",
  colorForButton: "#ff732B",
  colorForButtonHover: "#F35714",
  pagePadding: "90px",
  indent: "20px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  footerHeight: "80px",
  featureImageSize: "56px",
  pageWidth: "1280px",
  buttonColor: '#FC9B27',
  buttonColorHoverActive: '#FC7427',
  backgroundColorBlue: '#D8ECFE',
  backgroundColorGray: "#f7f7f7",
  panelBackgroundColor: "#88aa4d",
  headerHeight: "80px",
  footerHeight: "80px",
};